name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # O la rama que estás usando para desplegar

permissions:
  contents: write
  id-token: write  # Asegura que el permiso para id-token esté configurado

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
